#!/bin/bash
TARGET_DIR=~/YTDownloader  # Path to your working directory
GIT_DIR=~/YTDownloader.git  # Path to your bare repository
COMPOSE_DIR="/opt/docker-stack/"

echo "Deploying latest changes..."

# Checkout backend files
git --work-tree="${TARGET_DIR}" --git-dir="${GIT_DIR}" checkout --force main -- Android/Backend

# Navigate to the directory with docker-compose.yml and run it
cd "${COMPOSE_DIR}" || exit
docker compose up -d --build --remove-orphans --force-recreate ytdownloader

echo "Deployment complete."
